### ISSUE TITLE
Why can't I import the python files in other folders?

### ISSUE THREAD

**Issue by nemocandy5** [RobotLocomotion/pytorch-dense-correspondence#157]
Excuse me. I tried to run the notebook dense_correspondence/dataset/simple_datasets_test.ipynb
But it has import error. As shown below. If 22 lines are annotated, there are still similar problems in line 23 & line 24. How can I solve this?

![image](https://user-images.githubusercontent.com/31839757/44092454-0f360fdc-a003-11e8-8f91-30ccf1fab318.png)

**Comment by manuelli** [comment]
This is because you have not added the module onto your `PYTHONPATH`. Make sure you run `use_pytorch_dense_correspondence` and `use_director`. 

Before posting issues note that the tutorials are still under construction, and please check the readme's we have for setup. They explicitly mention the step about sourcing environment variables.

**Comment by peteflorence** [comment]
Hi @nemocandy5 -- just looking at this now, were you able to get this to work, or need any more help?  We also just posted a [tutorial](https://github.com/RobotLocomotion/pytorch-dense-correspondence/blob/master/doc/tutorial_getting_started.md) which might help you out.

Looking at the error message -- this may be the key command lines you need while setting up?

```
git submodule update --init --remote --recursive
git submodule update --recursive
```

Let me know if you have any more questions / issues.

**Comment by peteflorence** [comment]
And if not then yes, running `use_pytorch_dense_correspondence` in the terminal session will set your PYTHONPATH to be happy.  Should do this before starting a jupyter notebook server.
